### ISSUE TITLE
How to get base64-encoded token

### ISSUE THREAD

**Issue by hahattan** [biscuit-auth/biscuit-go#92]
From the sample code:
```go
...

b, err := builder.Build()
if err != nil {
    panic(fmt.Errorf("failed to build biscuit: %v", err))
}
token, err := b.Serialize()
if err != nil {
    panic(fmt.Errorf("failed to serialize biscuit: %v", err))
}
```

I tried
```go
fmt.Println(string(token))
```
and
```go
fmt.Println(base64.StdEncoding.EncodeToString(token))
```
Both output are not accepted by the online token-inspector tool

How do I transform `token` to a base64-encoded string so that I can share with other easily ?
Thanks for the help

**Comment by chilarai** [comment]
Did you find an answer to that?
I am unsure if `builder.Build()` generates invalid token or `b.Serialize()` has a problem

**Comment by Geal** [comment]
yes, we generally use URL safe base64 encoding. I'm opening https://github.com/biscuit-auth/biscuit/issues/128 to emphasize it
